name: CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Build
        run: go build -v .
